version: '3'
services:
  nodejs-server:
    build:
      context: ./
    ports:
      - "4001:3000"
    container_name: coffeebot-backend
    volumes:
       - ./:/usr/src/app/mrtgny/website
       - /usr/src/app/mrtgny/website/node_modules
